url: https://crst2023.github.io
baseurl: /

title: CSE Research Symposium
email: csrt2023@gmail.com
description: "Research Symposium for Computer Science. Date: 25-26 March 2023. Venue: F. C. Kohli Auditorium, IIT Bombay.."

people:
- name: Biswabandhan Panda
  pic: 1
  position: Professor
  social:
    - title: globe
      url: https://www.cse.iitb.ac.in/~biswa/
- name: Abir De
  pic: 2
  position: Professor
  social:
    - title: globe
      url: https://abir-de.github.io/
- name: Rohit Gurjar
  pic: 3
  position: Professor
  social:
    - title: globe
      url: https://www.cse.iitb.ac.in/~rgurjar/
# - name: Sarthak Mittal
#   pic: 4
#   position: Webpage Designer
#   social:
#     - title: globe
#       url: https://sarthakmittal92.github.io/

social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

address:
  - line: F.C. Kohli Auditorium, IIT Bombay, Powai
  - line: Mumbai, Maharashtra, India

markdown: kramdown
permalink: pretty
remote_theme: y7kim/agency-jekyll-theme